#############################################################################
# Makefile for building: bin/QuizDb
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sat Aug 20 22:39:57 2011
# Project:  QuizDb.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile QuizDb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/mainwindowimpl.cpp \
		src/main.cpp \
		src/errmsg.cpp \
		src/range.cpp \
		src/types.cpp \
		src/order.cpp \
		src/codes.cpp \
		src/quiz.cpp \
		src/quizedit.cpp \
		src/bible.cpp \
		src/quizview.cpp \
		src/quizmodel.cpp \
		src/questmodel.cpp \
		src/keyview.cpp \
		src/print.cpp \
		src/vrange.cpp \
		src/questclass.cpp build/moc_mainwindowimpl.cpp \
		build/moc_errmsg.cpp \
		build/moc_range.cpp \
		build/moc_types.cpp \
		build/moc_order.cpp \
		build/moc_codes.cpp \
		build/moc_quiz.cpp \
		build/moc_quizedit.cpp \
		build/moc_bible.cpp \
		build/moc_quizview.cpp \
		build/moc_quizmodel.cpp \
		build/moc_questmodel.cpp \
		build/moc_keyview.cpp \
		build/moc_print.cpp
OBJECTS       = build/mainwindowimpl.o \
		build/main.o \
		build/errmsg.o \
		build/range.o \
		build/types.o \
		build/order.o \
		build/codes.o \
		build/quiz.o \
		build/quizedit.o \
		build/bible.o \
		build/quizview.o \
		build/quizmodel.o \
		build/questmodel.o \
		build/keyview.o \
		build/print.o \
		build/vrange.o \
		build/questclass.o \
		build/moc_mainwindowimpl.o \
		build/moc_errmsg.o \
		build/moc_range.o \
		build/moc_types.o \
		build/moc_order.o \
		build/moc_codes.o \
		build/moc_quiz.o \
		build/moc_quizedit.o \
		build/moc_bible.o \
		build/moc_quizview.o \
		build/moc_quizmodel.o \
		build/moc_questmodel.o \
		build/moc_keyview.o \
		build/moc_print.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		QuizDb.pro
QMAKE_TARGET  = QuizDb
DESTDIR       = bin/
TARGET        = bin/QuizDb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_mainwindow.h build/ui_errdlg.h build/ui_rangedlg.h build/ui_orderdlg.h build/ui_formatdlg.h build/ui_quizdlg.h build/ui_printdlg.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QuizDb.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile QuizDb.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile QuizDb.pro

dist: 
	@$(CHK_DIR_EXISTS) build/QuizDb1.0.0 || $(MKDIR) build/QuizDb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/QuizDb1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/errmsg.h src/range.h src/types.h src/order.h src/codes.h src/quiz.h src/quizedit.h src/bible.h src/quizview.h src/quizmodel.h src/questmodel.h src/keyview.h src/print.h src/vrange.h src/questclass.h build/QuizDb1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.cpp src/main.cpp src/errmsg.cpp src/range.cpp src/types.cpp src/order.cpp src/codes.cpp src/quiz.cpp src/quizedit.cpp src/bible.cpp src/quizview.cpp src/quizmodel.cpp src/questmodel.cpp src/keyview.cpp src/print.cpp src/vrange.cpp src/questclass.cpp build/QuizDb1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/errdlg.ui ui/rangedlg.ui ui/orderdlg.ui ui/formatdlg.ui ui/quizdlg.ui ui/printdlg.ui build/QuizDb1.0.0/ && (cd `dirname build/QuizDb1.0.0` && $(TAR) QuizDb1.0.0.tar QuizDb1.0.0 && $(COMPRESS) QuizDb1.0.0.tar) && $(MOVE) `dirname build/QuizDb1.0.0`/QuizDb1.0.0.tar.gz . && $(DEL_FILE) -r build/QuizDb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwindowimpl.cpp build/moc_errmsg.cpp build/moc_range.cpp build/moc_types.cpp build/moc_order.cpp build/moc_codes.cpp build/moc_quiz.cpp build/moc_quizedit.cpp build/moc_bible.cpp build/moc_quizview.cpp build/moc_quizmodel.cpp build/moc_questmodel.cpp build/moc_keyview.cpp build/moc_print.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindowimpl.cpp build/moc_errmsg.cpp build/moc_range.cpp build/moc_types.cpp build/moc_order.cpp build/moc_codes.cpp build/moc_quiz.cpp build/moc_quizedit.cpp build/moc_bible.cpp build/moc_quizview.cpp build/moc_quizmodel.cpp build/moc_questmodel.cpp build/moc_keyview.cpp build/moc_print.cpp
build/moc_mainwindowimpl.cpp: src/vrange.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_errmsg.cpp: build/ui_errdlg.h \
		src/errmsg.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/errmsg.h -o build/moc_errmsg.cpp

build/moc_range.cpp: build/ui_rangedlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/range.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/range.h -o build/moc_range.cpp

build/moc_types.cpp: src/mainwindowimpl.h \
		src/vrange.h \
		src/types.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/types.h -o build/moc_types.cpp

build/moc_order.cpp: build/ui_orderdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/order.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/order.h -o build/moc_order.cpp

build/moc_codes.cpp: src/mainwindowimpl.h \
		src/vrange.h \
		src/codes.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/codes.h -o build/moc_codes.cpp

build/moc_quiz.cpp: build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quiz.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/quiz.h -o build/moc_quiz.cpp

build/moc_quizedit.cpp: src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizedit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/quizedit.h -o build/moc_quizedit.cpp

build/moc_bible.cpp: src/mainwindowimpl.h \
		src/vrange.h \
		src/bible.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/bible.h -o build/moc_bible.cpp

build/moc_quizview.cpp: src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/quizview.h -o build/moc_quizview.cpp

build/moc_quizmodel.cpp: src/quizview.h \
		src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/quizmodel.h -o build/moc_quizmodel.cpp

build/moc_questmodel.cpp: src/mainwindowimpl.h \
		src/vrange.h \
		src/questmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/questmodel.h -o build/moc_questmodel.cpp

build/moc_keyview.cpp: src/mainwindowimpl.h \
		src/vrange.h \
		src/keyview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/keyview.h -o build/moc_keyview.cpp

build/moc_print.cpp: build/ui_printdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/print.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/print.h -o build/moc_print.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow.h build/ui_errdlg.h build/ui_rangedlg.h build/ui_orderdlg.h build/ui_formatdlg.h build/ui_quizdlg.h build/ui_printdlg.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow.h build/ui_errdlg.h build/ui_rangedlg.h build/ui_orderdlg.h build/ui_formatdlg.h build/ui_quizdlg.h build/ui_printdlg.h
build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o build/ui_mainwindow.h

build/ui_errdlg.h: ui/errdlg.ui
	/usr/bin/uic-qt4 ui/errdlg.ui -o build/ui_errdlg.h

build/ui_rangedlg.h: ui/rangedlg.ui
	/usr/bin/uic-qt4 ui/rangedlg.ui -o build/ui_rangedlg.h

build/ui_orderdlg.h: ui/orderdlg.ui
	/usr/bin/uic-qt4 ui/orderdlg.ui -o build/ui_orderdlg.h

build/ui_formatdlg.h: ui/formatdlg.ui
	/usr/bin/uic-qt4 ui/formatdlg.ui -o build/ui_formatdlg.h

build/ui_quizdlg.h: ui/quizdlg.ui
	/usr/bin/uic-qt4 ui/quizdlg.ui -o build/ui_quizdlg.h

build/ui_printdlg.h: ui/printdlg.ui
	/usr/bin/uic-qt4 ui/printdlg.ui -o build/ui_printdlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		src/vrange.h \
		src/range.h \
		build/ui_rangedlg.h \
		src/types.h \
		src/order.h \
		build/ui_orderdlg.h \
		src/errmsg.h \
		build/ui_errdlg.h \
		src/quiz.h \
		build/ui_quizdlg.h \
		src/quizedit.h \
		src/questmodel.h \
		src/bible.h \
		src/print.h \
		build/ui_printdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/errmsg.o: src/errmsg.cpp src/errmsg.h \
		build/ui_errdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/errmsg.o src/errmsg.cpp

build/range.o: src/range.cpp src/range.h \
		build/ui_rangedlg.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/range.o src/range.cpp

build/types.o: src/types.cpp src/types.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/codes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/types.o src/types.cpp

build/order.o: src/order.cpp src/order.h \
		build/ui_orderdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/order.o src/order.cpp

build/codes.o: src/codes.cpp src/codes.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/codes.o src/codes.cpp

build/quiz.o: src/quiz.cpp src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizedit.h \
		src/quizview.h \
		src/questclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/quiz.o src/quiz.cpp

build/quizedit.o: src/quizedit.cpp src/quizedit.h \
		src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/quizedit.o src/quizedit.cpp

build/bible.o: src/bible.cpp src/bible.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/bible.o src/bible.cpp

build/quizview.o: src/quizview.cpp src/quizview.h \
		src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/quizmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/quizview.o src/quizview.cpp

build/quizmodel.o: src/quizmodel.cpp src/quizmodel.h \
		src/quizview.h \
		src/quiz.h \
		build/ui_quizdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/quizmodel.o src/quizmodel.cpp

build/questmodel.o: src/questmodel.cpp src/questmodel.h \
		src/mainwindowimpl.h \
		src/vrange.h \
		src/keyview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/questmodel.o src/questmodel.cpp

build/keyview.o: src/keyview.cpp src/keyview.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/keyview.o src/keyview.cpp

build/print.o: src/print.cpp src/questclass.h \
		src/print.h \
		build/ui_printdlg.h \
		src/mainwindowimpl.h \
		src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/print.o src/print.cpp

build/vrange.o: src/vrange.cpp src/vrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vrange.o src/vrange.cpp

build/questclass.o: src/questclass.cpp src/questclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/questclass.o src/questclass.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_errmsg.o: build/moc_errmsg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_errmsg.o build/moc_errmsg.cpp

build/moc_range.o: build/moc_range.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_range.o build/moc_range.cpp

build/moc_types.o: build/moc_types.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_types.o build/moc_types.cpp

build/moc_order.o: build/moc_order.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_order.o build/moc_order.cpp

build/moc_codes.o: build/moc_codes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_codes.o build/moc_codes.cpp

build/moc_quiz.o: build/moc_quiz.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_quiz.o build/moc_quiz.cpp

build/moc_quizedit.o: build/moc_quizedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_quizedit.o build/moc_quizedit.cpp

build/moc_bible.o: build/moc_bible.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_bible.o build/moc_bible.cpp

build/moc_quizview.o: build/moc_quizview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_quizview.o build/moc_quizview.cpp

build/moc_quizmodel.o: build/moc_quizmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_quizmodel.o build/moc_quizmodel.cpp

build/moc_questmodel.o: build/moc_questmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_questmodel.o build/moc_questmodel.cpp

build/moc_keyview.o: build/moc_keyview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_keyview.o build/moc_keyview.cpp

build/moc_print.o: build/moc_print.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_print.o build/moc_print.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

